### ISSUE TITLE
Float[] to Double[] bottle neck

### ISSUE THREAD

**Issue by YanYas** [MyCaffe/MyCaffe#10]
Hi,
using the Simple Datum I can setup my data relatively easily. Most of it comes as a float collection of some kind, but to change the simpledatum I need to use a double array. This means converting all of the elements of the array which seems like a bottle neck. Given that the system allows for floats and doubles as input, can the Cuda stage when the data is copied to GPU just copy a float if its the set datatype?

**Comment by ZoroDerVonCodier** [comment]
Hi @YanYas ,

Good point.  We will evaluate converting the SimpleDatum to use a template for the current double data and get back to you on this depending on the overall impact.  I agree that this would be a good optimization in that it would then avoid doing a double to float conversion.

**Comment by ZoroDerVonCodier** [comment]
Hi @YanYas ,
Ok, we have a plan on how to roll this in with minimal impact, however that roll-in will take a little time for we will be coordinating with overnight automatic testing for this change potentially impacts a lot of areas.  None the less, this is a good optimization which we have already started and will have completed in the next release.

**Comment by YanYas** [comment]
Hi @ZoroDerVonCodier ,
Thanks for looking into this. I can understand this might disrupt quite a bit of the codebase and tests, so I appreciate the effort.

**Comment by ZoroDerVonCodier** [comment]
Hi @YanYas ,
We have completed updating the SimpleDatum to now support both float and double.  The constructors and SetData method now control the type used (e.g. byte, float or double) and the various GetData methods allow for direct access or conversion if needed.  See https://github.com/MyCaffe/MyCaffe/blob/master/MyCaffe.basecode/SimpleDatum.cs for details.  We have just a few auto tests that we are working through related to this but this will definitely be in the next release that we are working on.  Thanks again for the feedback for this was a much needed improvement.

Hope this helps!

**Comment by YanYas** [comment]
You're welcome, looking forward to the update!

**Comment by YanYas** [comment]
Hi @ZoroDerVonCodier,
Yep that does the trick. Was thinking of something along the lines of a generic input (T[], List<T>) but but I guess people could get confused about what inputs are acceptable.

Closing, Thanks!

**Comment by ZoroDerVonCodier** [comment]
Hi @YanYas ,

That would be tempting, but we have found that at some point it is more efficient (as in the case of the SimpleDatum) to just have functions that support the specific types and therefore avoid any conversion - so for the sake of optimizing we went with the explicit types in the SimpleDatum.

Hope this helps!
