### ISSUE TITLE
AleControl version 010.1.149 nuget isn't available for build

### ISSUE THREAD

**Issue by YanYas** [MyCaffe/MyCaffe#11]
HI @ZoroDerVonCodier,

I'm trying to do a build for debug symbols, but MyCaffe.gym uses AleControl version 0.10.1.149 which isn't available (latest is 0.10.2.124).

**Comment by ZoroDerVonCodier** [comment]
Hi @YanYas ,

We have fixed this issue by upgrading the CudaControl in MyCaffe, the AleControl in MyCaffe.gym and the WebCam control in MyCaffe.layers.ssd to fix this issue - all are now set to use the release version 0.10.2.124.  Just sync to the latest on GitHub and you should be ready to go.

Hope this helps!

**Comment by YanYas** [comment]
Thank @ZoroDerVonCodier, I'll check it out!

**Comment by YanYas** [comment]
All good, thanks again
