### ISSUE TITLE
File not found - nccl64_134.10.0.dll

### ISSUE THREAD

**Issue by YanYas** [MyCaffe/MyCaffe#13]
When building the app, this error was returned:

> 1>  File not found - nccl64_134.10.0.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5165,5): error MSB3073: The command "%systemroot%\System32\xcopy /s /y "C:\MyCaffeRepo\MyCaffe_0_10_2_124\packages\HDF5DotNet.x64.1.8.9\NativeBinaries\*.*" "C:\MyCaffeRepo\MyCaffe_0_10_2_124\MyCaffe.app\bin\Debug\"
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5165,5): error MSB3073: %systemroot%\System32\xcopy /y C:\Data\Binaries\SS_Projects\_Debug\nccl64_134.10.0.dll "C:\MyCaffeRepo\MyCaffe_0_10_2_124\MyCaffe.app\bin\Debug\"" exited with code 4.

As a work around I copied the nccl from the installed version of  the MyCaffe App, created to corresponding folder and copied it in.

Then I noticed that the names were different (nccl64_134.**10**.0.dll, not nccl64_134.**12**.0.dll), the one in the app being later. So I changed the Mycaffe.App.proj file to rename the final output accordingly. I suspect your local drive or build server is setup a certain way to benefit from the hardcoded folder

**Comment by ZoroDerVonCodier** [comment]
Hi @YanYas ,
Good catch - I removed this from the project for we only use this locally.  However if you do want to use the multi-GPU support, you will need to copy the nccl64_134.10.2.dll into your bin directory (assuming that you are using the CUDA version 10.2).

**Comment by YanYas** [comment]
I see. Thanks again
