### ISSUE TITLE
Promotion Alliance

### ISSUE THREAD

**Issue by henon** [MyCaffe/MyCaffe#14]
Hello from SciSharp,

we are striving for creating a .NET based ML ecosystem and uniting library creators and would like to add your wonderful library MyCaffe to our [portal](http://www.scisharpstack.org). Would you agree to that? No strings attached.

**Comment by ZoroDerVonCodier** [comment]
Hi @henon ,

Sure - that would be great! Thank you for asking!

**Comment by ZoroDerVonCodier** [comment]
Hi @henon,

If you would, please point to the MyCaffe GitHub at https://github.com/MyCaffe/MyCaffe and MyCaffe on NUGET at https://www.nuget.org/packages/MyCaffe that way users can get the latest as we drop new updates.

Thanks!
