### ISSUE TITLE
 compute 5.0

### ISSUE THREAD

**Issue by Pigrecos** [MyCaffe/MyCaffe#17]
How come the set or sumsqdiff function doesn't work?
test on device:
GeForce GTX 750 Ti (2.14 GB - P2P off; compute 5.0)
up
CUDA 11.1.1, cuDNN 8.0.5

![immagine](https://user-images.githubusercontent.com/16204864/103299430-cd4e9e80-49fc-11eb-810e-c887e41413b6.png)

**Comment by ZoroDerVonCodier** [comment]
Hi @Pigrecos ,

It looks like you have not allocated the memory for hMem.  For a working sample that demonstrates how do do this in a similar manner to what you are trying to do, please see the new sample at:  https://github.com/MyCaffe/MyCaffe-Samples/blob/master/CudaDnn/CudaDnnTest/CudaDnnTest/Program.cs 

Note on line 24 which states:

hGpuMem = cuda.AllocMemory(1000);

That is what you are missing.  Once allocated, hGpuMem is then a handle to an array of 1000 floats in GPU memory.  Let us know if this works for you.

Hope this helps!

**Comment by Pigrecos** [comment]
thanks for the reply, but unfortunately it doesn't work
![immagine](https://user-images.githubusercontent.com/16204864/103630903-9cadbe00-4f42-11eb-9811-c9e03629ab28.png)

**Comment by ZoroDerVonCodier** [comment]
Hi @Pigrecos ,
We have updated the sample mentioned above with new status information on the GPU for which the sample is run.  Also we fixed an issue in the release version by changing that build to 64-bit.  Could you run that sample and post the results?  What NVIDIA driver version are you using?

Thanks!

**Comment by ZoroDerVonCodier** [comment]
Hi @Pigrecos ,
We found the problem.  The CudaDnnDll.11.1.dll that you are using, currently only supports compute 5.3 and up whereas you only have compute 5.0.  We have created a new CudaDnnDll.11.1 that now supports compute levels from 3.5 on up to 8.0.  You can download this new DLL here - [Multi SM/Compute CudaDnnDll.11.1](https://www.signalpop.com/beta-portal).  If all of our tests pass, our next release (due out this month) will have this new CudaDnnDll with multi Sm/Compute included in it.

Hope this helps!

**Comment by Pigrecos** [comment]
Thanks a lot, with the new dll it works perfectly

Output:

Creating CudaCuDnn...
GeForce GTX 750 Ti (2.14 GB - P2P off; compute 5.0)
GeForce GTX 750 Ti (Device: 0) -> TCC Driver = NO, 64bit = YES, Major = 5, Minor = 0, ComputeMode = 0, P2P Capable = NO, Cores = 640
 GPU = 0, MonitorOn = YES, GPU_Temp = 31 C°, GPU_Use = 0%
 Major: 5, Minor: 0, Compute Mode: 0
 Max Grid: { 2147483647, 65535, 65535 }, Max Thread Dim: { 1024, 1024, 64 }
 Shared Memory/Block: 49152

Allocate 1000 items...
Create memory pointers...
Test memory...
Memory test passed successfully!
Press any key to exit.

**Comment by ZoroDerVonCodier** [comment]
Hi @Pigrecos ,

That is good news!  Make sure to upgrade to the new MyCaffe when released, for the CudaDnnDll in that release will have gone through all of our tests.  I will leave this open until we make that next release.

**Comment by ZoroDerVonCodier** [comment]
Hi @Pigrecos ,
We recently released MyCaffe 0.11.2.9 which now has compute 3.5 through 8.0 support built in, eliminating the need for the special CudaDnnDLL mentioned above.  Thank for brining up this issue for adding the fix to the product is a good improvement!
