### ISSUE TITLE
How can I get Start Mycaffe?

### ISSUE THREAD

**Issue by futureflsl** [MyCaffe/MyCaffe#2]
I'm pleasure that MyCaffe is a good Framework for C#,But I don't konw how use it.Where is the document ,If some samples can be supplied,it will help Mycaffe's lovers.

**Comment by ZoroDerVonCodier** [comment]
Hi futureflsl,

The easiest way to get started is to download the MyCaffe Nuget package (https://www.nuget.org/packages?q=MyCaffe).  Once added to your Visual Studio project, you will see a new 'MyCaffeSample.cs' file which contains several static functions that show how to use MyCaffe.  For example, the static function 'MyCaffeSample.MyCaffeNeuralStyleSample.RunSample()' demonstrates creating art with the MyCaffe neural style.  

To learn more about using NUGET, please see https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio

Note, to run the MyCaffeSample.MyCaffeSample.RunSample(), which trains a model to learn the MNIST dataset, you will first need to create the MNIST dataset.  To do this, just run the MyCaffe Test Application, create the SQL database by selecting the 'Database | Create Database' menu, and then load the database with the MNIST dataset by selecting the 'Database | Load MNIST...' menu.  You only need to do these steps once.

Hope this helps!

**Comment by ZoroDerVonCodier** [comment]
Hi @futureflsl ,

We have recently started a new MyCaffe Programming Guide that you may find helpful to get you started.  The programming guide can be found at https://www.signalpop.com/docs.

Hope this helps!

**Comment by ZoroDerVonCodier** [comment]
@futureflsl ,

Correction, we moved the programming guide to https://www.signalpop.com/mycaffe/.
