### ISSUE TITLE
How to use pre-trained models to generate images?

### ISSUE THREAD

**Issue by zydjohnHotmail** [MyCaffe/MyCaffe#21]
Hello:
I can download all pre-trained models from NVIDIA for Stylegan3, for example: stylegan3-t-ffhqu-1024x1024.pkl
Then I can use the following Python code to generate images:
(stylegan3) C:\stylegan3>python gen_images.py --outdir=out --trunc=0.7 --seeds=600-605 --C:\stylegan3\stylegan3-t-ffhqu-1024x1024.pkl
The code can be downloaded from this URL:
https://github.com/NVlabs/stylegan3
Please advise on how I can do the job using the repo?

**Comment by ZoroDerVonCodier** [comment]
Hi @zydjohnHotmail ,

This should not be a problem as the model loads fine in the SignalPop AI Designer, see image.  I do see that the trained weights of the model are packed into an .h5 file format.  We currently do not support loading weights from .h5, but I will start looking into adding this as it definitely seems helpful.  We do support h5 file format, just not currently for loading model weights - adding this should not be a problem, so give me a few days to get this in and I will let you know. 

For more information on the SignalPop AI Designer, see https://www.signalpop.com/product_aidesigner

![stylegan](https://user-images.githubusercontent.com/24209639/161606783-5fd9a2c5-1e59-44f4-8d8d-d18cd468e086.png)

**Comment by zydjohnHotmail** [comment]
OK, thanks!

**Comment by ZoroDerVonCodier** [comment]
Hi @zydjohnHotmail ,

I have added in the support to load weights from HDF5 files.  To see an example on how to use this, check out the new test function 'TestHDF5LoadWts' at the bottom of  https://github.com/MyCaffe/MyCaffe/blob/master/MyCaffe.test/TestHDF5Layer.cs

This test function also shows how to load the prototxt for running the model in inference (e.g. no training).

Hope this helps!

**Comment by zydjohnHotmail** [comment]
Hello:
Do you have some pre-trained models I can do some testing with your code?
I prefer some image prediciton models, like StyleGan2/Stylegan3.
Thanks,

**Comment by ZoroDerVonCodier** [comment]
Hi @zydjohnHotmail ,

Check out the model referenced at https://github.com/BademiChetan/stylegan-encoder, their AFFACT-S.caffemodel.h5 appears to be pre-trained for the StyleGAN referenced on the GitHub site.  I have not used it other than testing loading the AFFACT model (AFFACT.prototxt and AFFACT-S.caffemodel.h5).  You might see if you can get that working first.  

Let me know how it goes and if you do get it working and you are willing to share your code, I could add it as a sample for MyCaffe.  We may add this later as a sample anyway as it looks like a pretty cool solution but that might be in awhile.

The new test loads the AFFACT.prototxt model and the AFFACT-S.caffemodel.h5 weights.

**Comment by zydjohnHotmail** [comment]
Hello:
I am trying to know how to use your code to load this AFFACT-S.caffemodel.h5 model, but since I am rather new with this type of model, I have a few questions to ask.

1) I want to use MyCaffe NUGET package, since I think it could be easier.
I created one C# console project with Visual Studio 2022, target .NET 5.0.
Then, I install the only NUGET package found:
PM> Install-Package MyCaffe -Version 0.11.6.86-beta1
First impression: this package is far away from 1.0 GA release, right?
Second, after I installed it, I got warning:
Warning	NU1701	Package 'AleControl 0.11.6.86-beta1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
I think .NETframework may be out of support very soon, even .NET 5.0, but .NET 6.0 is in long-term support, so it is better to use .NET 6.0 from now on.
Third, if the source code from the repo: https://github.com/MyCaffe/MyCaffe
can be used to make a new assembly, so I can reference it in .NET 5.0 console, can I simply change its target from .NETFrame 4.8 to .NET 5.0 or even .NET 6.0, which will save a lot of trouble later on.
If yes, then give me a general idea on how to go forward.

2) I downloaded AFFACT-S.caffemodel.h5 model, and open it with Netron version 5.6.7, and export the network as a PNG file.
You can take a look at the PNG file.  From my understand it seems to be not an image prediction network.
You can see another simple network picture: from this picture, it is easy to know the input and output.  But from the PNG file generated by Netron for AFFACT-S.caffemodel.h5 model, how I can know what is input/output?
In your load model program, how do you know which is input and which is output, if you look at the PNG model file?

3) Finally, the graphic card in my PC is NVIDIA Gefore GT1030, which NVIDIA even didn’t list it as CUDA-able graphic card.  So, in Python 3.9.7, when I want to generate some images using StyleGan3, I have to disable GPU. But my CPU has 32-core with 256GB ram, so I think my PC is powerful enough to do many things, besides, if I don’t need to train a model, just using pre-trained model, using GPU is not necessary. How I can use only CPU in MyCaffe repo?

Please advise,
Thanks,
![AFFACT-S](https://user-images.githubusercontent.com/45263518/161821578-2e95030b-298b-4198-88d2-9a900ca8bb3b.png)
![netron_browser_version](https://user-images.githubusercontent.com/45263518/161821619-b7753775-d9d3-4a73-8aac-da43c1801558.png)

**Comment by ZoroDerVonCodier** [comment]
Hi @zydjohnHotmail ,

Since I just added the support for loading weights from HDF5 files, that will new support not be in Nuget yet until we do our next Nuget update which we could do soon if needed.

Also, MyCaffe currently supports the .NET Framework 4.8 (e.g. not .NET Core), so you will want to create a Console Application that uses .NET Framework 4.8.  This should resolve many of the errors you are seeing.

Regarding 1.0 GA, we are close to that now but and do a full and extensive set of tests on each Nuget Release.  1.0 GA will happen this year though.

Regarding AFFACT-S.caffemodel.h5 – I have not dug into the details to see if it is an image prediction network or not, for I have only added the ability to import the weights.  The full AFFACT model is shown above in the graphic I posted.  If you open the AFFACT.prototxt model you can see that the input is an image of shape { 1,3,224,224 } which I presume is an image of a face.  The output is a set of attributes of shape { 1, 40, 1, 1 }.  I would have to dig into the article noted at karras2018stylegan-paper.pdf - Google Drive to find out how they are using the output and AFFACT model (if at all).
A GT1030 may not have enough memory to run any face model – or will only run at a very small batch size which will take a long time to train.  It may, however be able to run a pr-trained model.  You only have 2GB of video memory which is pretty small, so I’m not sure.

I will see if I can get a sample working with the AFFACT model and let you know the results.

**Comment by zydjohnHotmail** [comment]
Thanks and wait to hear good news from you!

**Comment by zydjohnHotmail** [comment]
Hello:
Any progress?

**Comment by ZoroDerVonCodier** [comment]
Hi @zydjohnHotmail ,

I have not made as much progress yet, for we have been very busy with a product release we are preparing to go public with in a few weeks, so that has taken priority.  However, I loaded the weights and had a looksee and they are definitely trained.

![stylegan_weights](https://user-images.githubusercontent.com/24209639/166121823-2630f38b-3d5e-4940-8b42-4c99e3a3febf.png)

My guess is that the output is some sort of embedding, but I will have to go through the article in detail to find out.  I'll be able to look at this more in detail later in May.

**Comment by zydjohnHotmail** [comment]
OK,
If you can figure out how to use the pre-trained model in C#, please let me know.
Thanks!

**Comment by zydjohnHotmail** [comment]
Hello:
Now, it is in June.  I hope you have some free time now.
Do you have any progress in using pre-trained model in C#.
Thanks,

**Comment by ZoroDerVonCodier** [comment]
Hi @zydjohnHotmail 
Not yet on this specific pre-trained model - sorry, still in the final push of our release.  I have not forgotten about you, but the releases are the top priority.  However, when we push out this next release, the NUGET version will have the new support for loading the pre-release model.

**Comment by zydjohnHotmail** [comment]
Hello:
If NUGET version will support pre-trained model, that will be great.
Any idea on when you will release it?
By the way, please provide some code sample on how to use pre-trained model to generate target images.
Thanks,

**Comment by ZoroDerVonCodier** [comment]
Hi @zydjohnHotmail ,

We have a new Nuget release that has included the ability to load weights from HDF5 files.  For an example on how to do this, see the TestHDF5LoadWts function on line 537 of https://github.com/MyCaffe/MyCaffe/blob/master/MyCaffe.test/TestHDF5Layer.cs.

I looked at the AFFACT model and how it is used as shown at the bottom of https://github.com/BademiChetan/stylegan-encoder/blob/master/Play_with_latent_directions.ipynb.  This model has 40 outputs that appear to map directly to the 40 attributes listed (e.g. '5_o_clock_Shadow', 'Arched_Eyebrows', ...). The very last block shows how these attributes are used but from what I could tell, unless I am missing something are not actually intput into the Gs_network.

The ipybn code has several errors that make it difficult of fully debug the code.  I realize this is not a full solution that you were hoping for, but that is what I have found out.

**Comment by zydjohnHotmail** [comment]
Hello:
I  want to know how to use the pre-trained model in C#, so I can use pre-trained model to predicate some picture in Style-GAN 3.
I took a look at the C# example, but I don't understand it much.
Do you have C# Code, which can use pre-trained model to predicate some picture in Style-GAN 3?
I can't use Python/ipynb, as my PC doesn't have useable GPU now, but my PC has 16-core CPU, so CPU using C# should be OK.
Please advise,
Thanks,
John

**Comment by ZoroDerVonCodier** [comment]
Hi @zydjohnHotmail ,

"Do you have C# Code, which can use pre-trained model to predicate some picture in Style-GAN 3?"
Currently, we do not, but I will let you know when we get something there.

"I can't use Python/ipynb, as my PC doesn't have useable GPU now, but my PC has 16-core CPU, so CPU using C# should be OK."

MyCaffe requires an NVIDIA GPU and can run on a very low cost GPU, such as https://www.amazon.com/EVGA-GeForce-Support-Graphics-04G-P4-6253-KR/dp/B01MF7EQJZ
