### ISSUE TITLE
Simplest FORWARD example?

### ISSUE THREAD

**Issue by Klanly** [MyCaffe/MyCaffe#3]
I'm trying  to use this to run some pre-trained models.
I don't need training/databases .etc.

In Opencv.dnn I can simply do:

```
Net net = dnn::readNetFromCaffe("bvlc_googlenet.prototxt", "bvlc_googlenet.caffemodel");
Mat inputBlob = blobFromImage(some_img_Mat, 1, Size(224, 224),
                              Scalar(104, 117, 123));
net.setInput(inputBlob);
Mat what_I_want = net.forward();
```

Now my code stuck here:

```
	static void caftet()
        {
       

            SettingsCaffe settings = new SettingsCaffe();
            settings.GpuIds = "0";  // use GPU 0.
            var mcaf = new MyCaffeControl<float>(settings, new Log("Test"), new CancelEvent());

            mcaf.m_net = new Net<float>() //???

//I made m_cuda & m_net public.

            
        }
```

How can I load .caffemodel file s ( they are protobuf binaries) into  `Net<T>`?
I searched the code I guess it's probably:

IXPersist.LoadSolverState(...), .caffemodel file as byte[] rgState.

But how can I make it link with MyCaffeControl.m_net?

Also need some explanation on how to fill input blob & get output blob manually.

**Comment by ZoroDerVonCodier** [comment]
@Klanly,

If you have not already done so, try downloading the MyCaffe Nuget package from https://www.nuget.org/packages?q=MyCaffe.  Once added to your Visual Studio project, you will see a sample file called MyCaffeSample.cs added to the project.

From within this file, take a look at the MyCaffeSample class and in specific the Initialize and Train methods.  

The Initialize method shows how to load the model and solver descriptors (which are added to a ProjectEx object) which is then used by the MyCaffeControl to load the internal Net and Solver that it maintains. 

For image data, the MyCaffeControl uses image datasets loaded into SQL (or SQLEXPRESS).  For example, the MyCaffe Test Application automatically loads the MNIST and CIFAR-10 datasets into SQL by selecting the MyCaffe Test Application's 'Database | Load MNIST...' and 'Database | Load CIFAR-10...' menu items.  The source code used to load these datasets is located at https://github.com/MyCaffe/AiDesigner/tree/master/dnn.net.dataset.mnist and https://github.com/MyCaffe/AiDesigner/tree/master/dnn.net.dataset.cifar_10.  Once in the database, the MyCaffeControl uses the MyCaffeImageDatabase which maintains an in-memory database of the images for fast retrieval during training.  Line 108 of the MyCaffeSample.cs which states "factory.LoadDataset("MNIST")" loads the descriptor of the MNIST dataset later used by the MyCaffeControl (and MyCaffeImageDatabase) to load all MNIST images into memory.

The MyCaffeControl manages the Net and Solver for you but if you want to directly access these see the MyCaffeControl.GetInternalNet(Phase p) method which will return one of three internal nets: Phase=TRAIN, returns the training net, Phase=TEST returns the testing net and Phase=RUN returns the Net to run.

And, to access the MyCaffeControl internal solver, see the MyCaffeControl.GetInternalSolver() method.

The MyCaffeControl methods are described at https://www.signalpop.com/onlinehelp/mycaffe/html/class_my_caffe_1_1_my_caffe_control.html

If you would rather roll your own image input you can do so by using an MEMORYDATA layer and call its AddDatumVector() method with an array of Datums, each of which contain an image.

Calling the method ImageData.GetImageData(bmp) loads the image data into a 1 or 3 channel Datum.  For more information on this class, see https://www.signalpop.com/onlinehelp/mycaffe/html/class_my_caffe_1_1basecode_1_1_image_data.html

For more online documentation, see https://www.signalpop.com/onlinehelp/mycaffe/html/index.html which is generated on each build.

Hope this helps!

**Comment by ZoroDerVonCodier** [comment]
We have just added a new Git project called MyCaffe-Samples.  From within that sample, check out the file https://github.com/MyCaffe/MyCaffe-Samples/blob/master/ImageClassification/ImageClassification/MainForm.cs

In this file, you will find three different examples showing how to use MyCaffe for simple classification:

1.) Simple Classification - directly uses the internal Net and Solver managed by the MyCaffeControl to perform classification.

2.) Simpler Classification - directly only uses the internal Solver managed by the MyCaffeControl to perform classification.

3.) Simplest Classification - uses the MyCaffeControl and MyCaffeImageDatabase to perform classification.

To run these you will need to install the MyCaffe Test Application and SQL (or SQLEXPRESS), create the DNN database (Database | Create.. menu) and load the MNIST dataset (Database Load MNIST... menu).

Next, you will need to export the MNIST images to file (from the MyCaffe-Sample), which is only necessary to run the first two samples.  The Simplest Classification uses the already loaded MNIST database and therefore does not require exporting of the MNIST images.

Hope these help!

**Comment by ZoroDerVonCodier** [comment]
@Klanly ,
We have started a new MyCaffe Programming Guide that you may find helpful, please see
https://www.signalpop.com/mycaffe/

Hope this helps!
