### ISSUE TITLE
Onnx

### ISSUE THREAD

**Issue by YanYas** [MyCaffe/MyCaffe#5]
Hi, 
Will it be possible to export ONNX models?

**Comment by ZoroDerVonCodier** [comment]
Hi @YanYas,

Not yet, but we will look into it.  Thanks for letting us know about ONNX!

**Comment by ZoroDerVonCodier** [comment]
Hi @YanYas ,

According to https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/converter_scripts/caffe_coreml_onnx.ipynb you should be able to convert between the CAFFE proto-text models and ONNX.  MyCaffe uses the same CAFFE proto-text files for its models so as long as you use CAFFE supported MyCaffe layers, you should be able to convert your model to ONNX and from ONNX to the CAFFE proto-text files.

Let us know how this works for you if you try it.

Hope this helps!

**Comment by ZoroDerVonCodier** [comment]
@YanYas ,

I forgot to mention that MyCaffe supports both the CAFFE proto-text format for descriptors AND the binary caffemodel format for CAFFE models.

Hope this helps!

**Comment by YanYas** [comment]
V. cool, thanks for finding this! 

I realised about the binary caffemodel format while I was traveling through docs. I'll feedback soon.

**Comment by ZoroDerVonCodier** [comment]
@YanYas ,
We just added extensive ONNX support for both import and export in the new release that we just dropped.  You can now export MyCaffe models to *.onnx files and import *.onnx files to create new MyCaffe models.  See https://www.signalpop.com/2020/06/01/onnx-ai-model-format-now-supported-by-the-signalpop-ai-designer/ for more details.

**Comment by YanYas** [comment]
Wow, that was more than I was expecting or hoped for (import!). I switched jobs recently, so I haven't had time to work with you library lately, but I have been making plans and this is nice added motivation :-D
Phenomenal, bravo!
