### ISSUE TITLE
Guidance needed for setting up MemoryDataLayer

### ISSUE THREAD

**Issue by YanYas** [MyCaffe/MyCaffe#9]
Hi,

I've been trying to set data into the layer pipeline. I tried the MemoryDataLayer but it threw an exception - '[there] are not enough datum to add'. Digging further I realized this was because the datum list count / the batch_size were unequal to or less than '1'. 

I could set the batch size from the layer itself, but other channels couldn't be updated, which I think I understand. This meant that AddDatumVector expected 1,0,0,0 input shape. Example below:

    class MemDataTest
    {
        public static MemoryDataLayer<float> createMemDatalayer(CudaDnn<float>cuda, Log log)
        {
            // Create the parameters for the MemoryData itself
            var myMemParam = new MemoryDataParameter();
            myMemParam.label_type = LayerParameterBase.LABEL_TYPE.ONLY_ONE;
            myMemParam.batch_size = 1;
            myMemParam.channels = 1;
            myMemParam.height = 1;
            myMemParam.width = 60; // <- the true size of the data

            // Create layer parameter
            var mylayerParam = new LayerParameter(LayerParameter.LayerType.MEMORYDATA);
            mylayerParam.memory_data_param = myMemParam;

            // Create MemoryLayer itself
            var ramDataLayer = new MemoryDataLayer<float>(cuda, log, mylayerParam);
            return ramDataLayer;
        }

        public static List<Datum> DataSetter(CudaDnn<float> cuda, Log log)
        {
            // Setup input data values as an array of floats
            var myRamData = new float[60];

            for (int i = 0; i < myRamData.Length; i++)
            {
                myRamData[i] = 10;
            }

            // Set a shape for the data
            var dShape = new BlobProto(new List<int> { 1, 1, 1, 60 });
            var dBlob = new Blob<float>(cuda, log, dShape, false);
            dBlob.mutable_cpu_data = myRamData;
            var myDatumVec = new List<Datum>();
            myDatumVec.Add(dBlob.ToDatum());

            return myDatumVec;
        }

        public static MemoryDataLayer<float> DataInserter(MemoryDataLayer<float> myInputLayer, List<Datum> DatumVec)
        {
            Console.WriteLine("My input layer has a batch size of (0) and a width of {1}", myInputLayer.batch_size, myInputLayer.width);
            // The parameters haven't been read.
            // I can change the intended batch size here and it will take effect.
            myInputLayer.batch_size = 1;
            Console.WriteLine("My input layer has a batch size of (0) and a width of {1}", myInputLayer.batch_size, myInputLayer.width);
            // But I can't set the width or the other dimensions this way.
            // myInputLayer.width = 1;
            // Let's set the batch to '0' again.
            myInputLayer.batch_size = 0;
            //and we will get the first error '[there] are not enough datum to add'
            myInputLayer.AddDatumVector(DatumVec); // you can comment out this line
            myInputLayer.batch_size = 1;
            myInputLayer.AddDatumVector(DatumVec);
            return myInputLayer;
        }

        public static void TheTest()
        {
            var myDevice = new CudaDnn<float>(0, DEVINIT.CURAND);
            var myLog = new Log("Test");

            var memlayer = createMemDatalayer(myDevice, myLog);
            var data = DataSetter(myDevice, myLog);
            memlayer = DataInserter(memlayer, data);

        }
    }
}

My IDE is a little strange sometimes but do you see something similar? Could I work with BlobCollections in the meanwhile?

Yy

**Comment by ZoroDerVonCodier** [comment]
Hi @YanYas ,

We have added a new sample that shows how to use the MemoryDataLayer at https://github.com/MyCaffe/MyCaffe-Samples/tree/master/MemoryDataLayer.

At a real high level, it looks like you are getting the CPU and GPU data mixed up a bit in data setter.  For more discussion on how MyCaffe moves CPU data to the GPU, see new new MyCaffe Programming Guide that we are working on at https://www.signalpop.com/docs.  This may give you some helpful insights.  Just remember that data always flows from the SimpleDatum or Datum (which only hold CPU memory) to the Blob (which manages the GPU memory).  Once the data is on the GPU, we like to keep it there for it is much more efficient to manipulate the data on the GPU and only transfer it back to the CPU when really needed for the CPU <-> GPU transfer can be expensive.

Internally, the MemoryDataLayer takes care of doing this transfer when you call its AddDataumVector method.  This method takes care of transforming the data with the DataTransformer (or its default) and then fills its internal data and label blobs which are then used to load the top blobs during each forward pass.

Hope this helps!

**Comment by YanYas** [comment]
Hi Zoro, that has helped me significantly narrow down the problem. There is something going on with my [IDE](https://visualprogramming.net/), could be to do with the version of dotnet it uses. I'll try and investigate further, but we can consider this issue closed.

Thanks again,
Yy

(PS I tried to build the git repo to debug the issue but 

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot import the following key file: mycaffe.basecode.sn.pfx. The key file may be password protected. To correct this, try to import the certificate again or manually install the certificate to the Strong Name CSP with the following key container name: VS_KEY_CAABA683E90E9E7F	MyCaffe.basecode			

and another for MyCaffe's main library

**Comment by YanYas** [comment]
So my mistake was using the DataLayerSetup function instead of 'Setup'. 'DataLayerSetup' doesn't have a DataTransformer<T>property so when it AddDatumVector tries to use DataTransform it simply isn't available.

**Comment by ZoroDerVonCodier** [comment]
Hi @YanYas ,

Yes, using the DataLayerSetup directly would cause a problem, but also highlighted to us that this should have been 'protected' for it is not intended for direct use.  For that reason we have changed this function to protected.
